<?php 
session_start();

?>

<?php 
// if (!isset($_POST['signin'])) {
// 	if ($_SESSION['highstake']=="yes") {
// 		echo '<h1><b>You don\'t have that kind of cash</b></h1>';
// 	}else{
// 		$_SESSION['highstake']="no";
// 	}
// }


?>	
	
<?php 

if (isset($_POST['signin']) ) {
	extract($_POST);
// 	session_unset();

// // destroy the session
// session_destroy();

	$conn=mysqli_connect("localhost","Samuel","samuel3333","bettingsite");
	if (!$conn) {
		die("Connection failed: " . mysqli_connect_error());
	}
	$select="SELECT telephone,password FROM registration";
	$result = mysqli_query($conn, $select);
	while($row = mysqli_fetch_assoc($result)) {
		if ($row['telephone']==$telephone and $row['password']==$pass) {
			?>

			<!DOCTYPE html>
			<html>
			<head>
				<title>Casino</title>
				<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.css">
				<style type="text/css">
					body{
						background-color: pink;
					}
				</style>
			</head>
			<body>


				<div class="container">
					<nav class="navbar navbar-inverse ">
							<div class="container-fluid">
								<div class="navbar-header">

								</div>
								<ul class="nav navbar-nav">


								</ul>
								<ul class="nav navbar-nav navbar-right">

									<li><a class="btn btn-lg" href="index.php"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
								</ul>
							</div>
						</nav>
					<div class="jumbotron">
						<hr>
						<p class="text-right">
							<?php 
							$_SESSION['access']="granted";
							$select="SELECT name,telephone,money FROM registration";
							$table=mysqli_query($conn,$select);
							while ($row=mysqli_fetch_assoc($table)) {
								if ($row['telephone']==$telephone) {
									echo "<b>Hello:</b>".$row['name']."<br>";
									echo $telephone."<br>";
									$_SESSION['maxstake']=$row['money'];
									$_SESSION['telephone']=$telephone;
									
									echo"<b>KSH:</b> " . $row['money'];
								}
							}


							?>



						</p>
						<hr>
						<form method="post" action="slip.php" >
							<div class="form-group">
								<label>
									<h3><b>Stake:</b></h3><input type="number" class="form-control" name="stake" max="
									<?php 

									echo $maxstake;
									?>
									">
								</label>
							</div>
							<div class="form-group">
								<p>(choose whether the random number generated by the computer is odd or even)</p>
								<select name="chosen" class="form-control">
									<option value="none" ></option>
									<option value="odd"><b>Odd</b></option>
									<option value="even"><b>Even</b></option>
								</select>
							</div>
							<input type="submit" value="BETNOW" name="submit" class="btn btn-lg btn-success">

						</form>




					</div>
					<div class="jumbotron">
			<h1 class="text-center"><span class="text-success">C</span>AS<span class="text-danger">INO</span></h1>
			<h3 class="text-center"><span class="text-success">WIN</span>|WIN <span class="text-danger">WIN</span> </h3>

		</div>

				</div>


			</body>
			</html>


			<?php  	die();}

		}
		$_SESSION['access']="denied";
		header('Location:index.php');
		die('No such user or wrong password');
	}
	?>
	<?php 
	if ($_SESSION['telephone']) {

		$conn=mysqli_connect("localhost","Samuel","samuel3333","bettingsite");
		$telephone=$_SESSION['telephone'];

		$select="SELECT telephone FROM registration";
		$table=mysqli_query($conn,$select);
		while ($row=mysqli_fetch_assoc($table)) {
			if ($row['telephone']==$telephone) {
				$_SESSION['access']="granted";
				?><!DOCTYPE html>
				<html>
				<head>
					<title>Casino</title>
					<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.css">
					<style type="text/css">
					body{
						background-color: pink;
					}
				</style>
					
				</head>
				<body>


					<div class="container">
						<nav class="navbar navbar-inverse ">
							<div class="container-fluid">
								<div class="navbar-header">

								</div>
								<ul class="nav navbar-nav">


								</ul>
								<ul class="nav navbar-nav navbar-right">

									<li><a class="btn btn-lg" href="index.php"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
								</ul>
							</div>
						</nav>

						
						<div class="jumbotron">
							<h3 class="text-center text-danger"><?php 
							if (!isset($_POST['signin'])) {
								if ($_SESSION['highstake']=="yes") {
									echo 'You don\'t have that kind of cash!!';
								}else{
									$_SESSION['highstake']="no";
								}
							}

							 ?></h3>
							<div>
								<?php 
								if ($_SESSION['newuser']==true) {
									?>
									<h2 class="text-success">Welcome to the club,you have succesfully signed up.You have free Ksh 500!</h2>		
									<?php 
								}else{

								}

								?>

								
							</div>
							<hr>
							<p class="text-right ">
								<?php 
								$select="SELECT name,telephone,money FROM registration";
								$table=mysqli_query($conn,$select);
								while ($row=mysqli_fetch_assoc($table)) {
									if ($row['telephone']==$telephone) {

										echo "<b>Hello:</b>".$row['name']."<br>";
										$_SESSION['maxstake']=$row['money'];
										$_SESSION['telephone']=$telephone;
										echo $telephone."<br>";
										echo"<b>KSH:</b> " .$row['money'];
									}
								}


								?>



							</p>
							<hr>
							<form method="post" action="slip.php" >
								<div class="form-group">
									<label>
										<h3><b>Stake:</b></h3><input type="number" class="form-control" name="stake" max="
										">

										 
									</label>
								</div>
								<div class="form-group">
									<p>(choose whether the random number generated by the computer is odd or even)</p>
									<select name="chosen" class="form-control">
										<option value="none"></option>
										<option value="odd"><h2>Odd</h2></option>
										<option value="even"><h2>Even</h2></option>
									</select>
								</div>
								<input type="submit" value="BETNOW" name="submit" class="btn btn-lg btn-success">

							</form>



						</div>
						<div class="jumbotron">
							<h1 class="text-center"><span class="text-success">C</span>AS<span class="text-danger">INO</span></h1>
							<h3 class="text-center"><span class="text-success">WIN</span>|WIN <span class="text-danger">WIN</span> </h3>

						</div>

					</div>


				</body>
				</html>



				<?php 
			}
		}
		die();
	}

	?>


	?>				

